name: Grave Ambition
favicon: null
layout_spectrum: 0.77323
typography_spectrum: 0.20232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4b2e4b'
    - '#f7f361'
    - '#f089a0'
    - '#2eecdb'
    - '#e6c6e5'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.28024797490797937
purpose: []
