name: Grave Ambition
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20232
title: Grave Ambition
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4b2e4b'
    - '#f7f361'
    - '#f089a0'
    - '#2eecdb'
    - '#e6c6e5'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
