name: Grave Ambition
favicon: null
layout_spectrum: 0.49725
typography_spectrum: 0.72464
title: Grave Ambition
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#545452'
    - '#030708'
    - '#929290'
    - '#ce2127'
    - '#612a23'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
